CASES="
asdas sad  fff fff ff f   fghjhg
\na aa aaa aaaa aaaaa aaaaaa aaaaaaa aaaaaaaa aaaaaaaaa aaaaaaaaaa aaaaaaaaaaa aaaaaaaaaaaa
\na aa aaa aaaa aaaaa aaaaaa aaaaaaa aaaaaaaa aaaaaaaaa aaaaaaaaaa aaaaaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaa aaaaaaaaaaaaaa aaaaaaaaaaaaaaa aaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaa
\na aa aaa aaaa aaaaa aaaaaa aaaaaaa aaaaaaaa aaaaaaaaa aaaaaaaaaa aaaaaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaa aaaaaaaaaaaaaa aaaaaaaaaaaaaaa aaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
\n
\n
\n7DvZJER 7DvZJER 7DvZJER 7DvZJER
\nN6MMzV3VwFbAxkCr N6MMzV3VwFbAxkCr N6MMzV3VwFbAxkCr N6MMzV3VwFbAxkCr N6MMzV3VwFbAxkCr N6MMzV3VwFbAxkCr N6MMzV3VwFbAxkCr

\noOPdBZtzGy9J7H0xy LBdAVX4eL7gM88ljerMK0tJ5cNLV3gXV78g oOPdBZtzGy9J7H0xy LBdAVX4eL7gM88ljerMK0tJ5cNLV3gXV78g oOPdBZtzGy9J7H0xy LBdAVX4eL7gM88ljerMK0tJ5cNLV3gXV78g oOPdBZtzGy9J7H0xy LBdAVX4eL7gM88ljerMK0tJ5cNLV3gXV78g oOPdBZtzGy9J7H0xy LBdAVX4eL7gM88ljerMK0tJ5cNLV3gXV78g oOPdBZtzGy9J7H0xy LBdAVX4eL7gM88ljerMK0tJ5cNLV3gXV78g oOPdBZtzGy9J7H0xy LBdAVX4eL7gM88ljerMK0tJ5cNLV3gXV78g
\nm5pHxgcBH2xRg5LxiF95xPNIsSZ1vvW5aabR m5pHxgcBH2xRg5LxiF95xPNIsSZ1vvW5aabR m5pHxgcBH2xRg5LxiF95xPNIsSZ1vvW5aabR m5pHxgcBH2xRg5LxiF95xPNIsSZ1vvW5aabR
\nUjmatRDJqHydd7lCqPRbEoP4tSUqL UjmatRDJqHydd7lCqPRbEoP4tSUqL UjmatRDJqHydd7lCqPRbEoP4tSUqL
\n1qNXl4Zac 1qNXl4Zac 1qNXl4Zac
\nrPmGRWGCcWX0t8TV0p8MN0XQBDAln9 rPmGRWGCcWX0t8TV0p8MN0XQBDAln9 rPmGRWGCcWX0t8TV0p8MN0XQBDAln9 rPmGRWGCcWX0t8TV0p8MN0XQBDAln9 rPmGRWGCcWX0t8TV0p8MN0XQBDAln9 rPmGRWGCcWX0t8TV0p8MN0XQBDAln9 rPmGRWGCcWX0t8TV0p8MN0XQBDAln9
\nDfEvZeSavoYC DfEvZeSavoYC
\nTK    WLRAQ0u 5ztK92y jVqKb
\ncqAlNiUfPINoQ  EeTKER7I77He2nHdWT5N4EUphdgGUvqT cqAlNiUfPINoQ  EeTKER7I77He2nHdWT5N4EUphdgGUvqT cqAlNiUfPINoQ  EeTKER7I77He2nHdWT5N4EUphdgGUvqT cqAlNiUfPINoQ  EeTKER7I77He2nHdWT5N4EUphdgGUvqT cqAlNiUfPINoQ  EeTKER7I77He2nHdWT5N4EUphdgGUvqT
\n      cPGBfquH23qfqAAwI2      CjBj1T7Bbc4Bb5vRx7spBJHGK7P 6DKK5YdOAQY2Zv7
\nDQBqQaVm DQBqQaVm DQBqQaVm DQBqQaVm DQBqQaVm DQBqQaVm DQBqQaVm
\n4FR   4QT5wP
\nAV3Pe5q54hkBGRZ8U     7o9WXB  FMc5fRbZlVgPDyiPUToBYr0E5t2J AV3Pe5q54hkBGRZ8U  7o9WXB  FMc5fRbZlVgPDyiPUToBYr0E5t2J AV3Pe5q54hkBGRZ8U  7o9WXB  FMc5fRbZlVgPDyiPUToBYr0E5t2J AV3Pe5q54hkBGRZ8U  7o9WXB  FMc5fRbZlVgPDyiPUToBYr0E5t2J AV3Pe5q54hkBGRZ8U  7o9WXB  FMc5fRbZlVgPDyiPUToBYr0E5t2J AV3Pe5q54hkBGRZ8U  7o9WXB  FMc5fRbZlVgPDyiPUToBYr0E5t2J AV3Pe5q54hkBGRZ8U 7o9WXB   FMc5fRbZlVgPDyiPUToBYr0E5t2J
\nxLNmwp        l1C8djpKb7qhw ZThiyy sym4 xLNmwp        l1C8djpKb7qhw ZThiyy sym4 xLNmwp        l1C8djpKb7qhw ZThiyy sym4 xLNmwp        l1C8djpKb7qhw ZThiyy sym4
\nQcq2CCy8Jp    H3CU9jA4xwLHfrQB Qcq2CCy8Jp     H3CU9jA4xwLHfrQB
\nSfkgOSanQScFBl8JOIS   jpmBCLu3j3IVD8ES SfkgOSanQScFBl8JOIS    jpmBCLu3j3IVD8ES SfkgOSanQScFBl8JOIS    jpmBCLu3j3IVD8ES

\nqldENCmyiGtokubrSqML04PtfFGqZ fkmVIHhq                DCQS 8ZljZpfve95ZYC qldENCmyiGtokubrSqML04PtfFGqZ       fkmVIHhDCQS 8ZljZpfve95ZYC qldENCmyiGtokubrSqML04PtfFGqZ        fkmVIHhq                DCQS 8ZljZpfve95ZYC qldENCmyiGtokubrSqML04PtfFGqZ       fkmVIHhq                DCQS 8ZljZpfve95ZYC qldENCmyiGtokubrSqML04PtfFGqZ       fkmVIHhq               DCQS 8ZljZpfve95ZYC
\n4pQpX1 4pQpX1 4pQpX1 4pQpX1 4pQpX1 4pQpX1 4pQpX1
\nsP1bE AuDovasw0ZDko5O Kj5aLQgoa13U1UIwxfN7L9tPRr94xWskOIL4wUvjVSEK sP1bE AuDovasw0ZDko5O Kj5aLQgoa13U1UIwxfN7L9tPRr94xWskOIL4wUvjVSEK sP1bE AuDovasw0ZDko5O Kj5aLQgoa13U1UIwxfN7L9tPRr94xWskOIL4wUvjVSEK sP1bE AuDovasw0ZDko5O Kj5aLQgoa13U1UIwxfN7L9tPRr94xWskOIL4wUvjVSEK sP1bE AuDovasw0ZDko5O Kj5aLQgoa13U1UIwxfN7L9tPRr94xWskOIL4wUvjVSEK sP1bE AuDovasw0ZDko5O Kj5aLQgoa13U1UIwxfN7L9tPRr94xWskOIL4wUvjVSEK sP1bE AuDovasw0ZDko5O Kj5aLQgoa13U1UIwxfN7L9tPRr94xWskOIL4wUvjVSEK
\nLuML9ZSw3vdNAPiJ OAi1f3uSAjhKvbQ9rDB8mmAnf9pr LuML9ZSw3vdNAPiJ OAi1f3uSAjhKvbQ9rDB8mmAnf9pr LuML9ZSw3vdNAPiJ OAi1f3uSAjhKvbQ9rDB8mmAnf9pr LuML9ZSw3vdNAPiJ OAi1f3uSAjhKvbQ9rDB8mmAnf9pr LuML9ZSw3vdNAPiJ OAi1f3uSAjhKvbQ9rDB8mmAnf9pr LuML9ZSw3vdNAPiJ OAi1f3uSAjhKvbQ9rDB8mmAnf9pr
\nunnRBSOEbF    fUQ0L1qGr30 unnRBSOEbF  fUQ0L1qGr30 unnRBSOEbF  fUQ0L1qGr30
\nlc17X7J7DB6zbARVAMpYg lc17X7J7DB6zbARVAMpYg
\nu8jk3R5Y1t5DARL9YcYvJKi7kylb634Bm     fVRFs8rUliG i2W2XNW     jfHcxD9gwx      RDA 9
\n3MO6Kq0axfWAv
\nZOCqOldmdRSY6FJ5GQjCAQN ZOCqOldmdRSY6FJ5GQjCAQN ZOCqOldmdRSY6FJ5GQjCAQN ZOCqOldmdRSY6FJ5GQjCAQN ZOCqOldmdRSY6FJ5GQjCAQN
\nkXfEzT926QBZVzaz0dQAjzI3N938tiDK11z27k0nEGXFKFKH5bmNM kXfEzT926QBZVzaz0dQAjzI3N938tiDK11z27k0nEGXFKFKH5bmNM
\nmv    6bWUqvSN65J5MON0guDRVF0JTuLUUoehytiMkAcz4oAk bNlA7a32kYNl mv    6bWUqvSN65J5MON0guDRVF0JTuLUUoehytiMkAcz4oAk bNlA7a32kYNl
\nC C
\nm m
"

echo ""
echo "==================="
echo "= Custom readline ="
echo "==================="
echo ""

./build.sh
OUT1=$(echo -e $CASES | ./main)
echo -e "$OUT1"

echo ""
echo "================"
echo "= GNU readline ="
echo "================"
echo ""

./build.sh 1
OUT2=$(echo -e $CASES | ./main)
echo -e "$OUT2"

python -c "import re;
matches = re.findall(r'Words found: \"(.*)\"(?:.|\n)+Total: (\d+\.\d+) seconds', input());
for match in matches:
    print(match.group(1), match.group(1))

"
